<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-11 at 19:42:04.
 */
class FactoryTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Factory
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Factory;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Factory::getInstance
     * @todo   Implement testGetInstance().
     */
    public function testGetInstance() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::createPlateau
     * @todo   Implement testCreatePlateau().
     */
    public function testCreatePlateau() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::createRover
     * @todo   Implement testCreateRover().
     */
    public function testCreateRover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Factory::createMovement
     * @todo   Implement testCreateMovement().
     */
    public function testCreateMovement() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
