<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-11 at 19:42:30.
 */
class PlateauTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Plateau
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Plateau;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Plateau::getPlateau
     * @todo   Implement testGetPlateau().
     */
    public function testGetPlateau() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
