<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-11 at 19:42:36.
 */
class RoverTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Rover
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Rover;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rover::getRover
     * @todo   Implement testGetRover().
     */
    public function testGetRover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rover::setRover
     * @todo   Implement testSetRover().
     */
    public function testSetRover() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
