<?php

/**
 * Generated by PHPUnit_SkeletonGenerator on 2019-05-11 at 19:42:23.
 */
class MovementTest extends PHPUnit_Framework_TestCase {

    /**
     * @var Movement
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Movement;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Movement::turnLeft
     * @todo   Implement testTurnLeft().
     */
    public function testTurnLeft() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Movement::turnRight
     * @todo   Implement testTurnRight().
     */
    public function testTurnRight() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Movement::moveForward
     * @todo   Implement testMoveForward().
     */
    public function testMoveForward() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
